# Numpy Project 1:

Student Performance Analysis Using Numpy

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nabeelqureshitiii/student-performance-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'student-performance-dataset' dataset.
Path to dataset files: /kaggle/input/student-performance-dataset


In [2]:
import numpy as np

num_data = np.genfromtxt('/kaggle/input/student-performance-dataset/student_performance.csv', delimiter=',', skip_header=1)
full_data = np.genfromtxt('/kaggle/input/student-performance-dataset/student_performance.csv', delimiter=',', dtype=str)

In [3]:
num_data = num_data[:, 0:5]
num_data

array([[1.00000e+00, 1.85000e+01, 9.56000e+01, 3.80000e+00, 9.79000e+01],
       [2.00000e+00, 1.40000e+01, 8.00000e+01, 2.50000e+00, 8.39000e+01],
       [3.00000e+00, 1.95000e+01, 8.63000e+01, 5.30000e+00, 1.00000e+02],
       ...,
       [9.99998e+05, 1.42000e+01, 8.51000e+01, 5.80000e+00, 8.79000e+01],
       [9.99999e+05, 2.53000e+01, 9.00000e+01, 5.30000e+00, 1.00000e+02],
       [1.00000e+06, 1.83000e+01, 8.46000e+01, 4.10000e+00, 1.00000e+02]])

In [4]:
full_data

array([['student_id', 'weekly_self_study_hours', 'attendance_percentage',
        'class_participation', 'total_score', 'grade'],
       ['1', '18.5', '95.6', '3.8', '97.9', 'A'],
       ['2', '14.0', '80.0', '2.5', '83.9', 'B'],
       ...,
       ['999998', '14.2', '85.1', '5.8', '87.9', 'A'],
       ['999999', '25.3', '90.0', '5.3', '100.0', 'A'],
       ['1000000', '18.3', '84.6', '4.1', '100.0', 'A']], dtype='<U23')

In [5]:
np.isnan(num_data).sum()

np.int64(0)

In [6]:
mean = np.mean(num_data, axis=0)
mean

array([5.00000500e+05, 1.50291269e+01, 8.47110460e+01, 5.98520260e+00,
       8.42838453e+01])

Average of these columns

In [7]:
print("Mean of each column:", mean)
print("Average Weekly Self Study Hours: ", mean[1].round(2))
print("Average Attendence Percentage: ", mean[2].round(2))
print("Average Class Participation: ", mean[3].round(2))
print("Average Total Score: ", mean[4].round(2))

Mean of each column: [5.00000500e+05 1.50291269e+01 8.47110460e+01 5.98520260e+00
 8.42838453e+01]
Average Weekly Self Study Hours:  15.03
Average Attendence Percentage:  84.71
Average Class Participation:  5.99
Average Total Score:  84.28


In [8]:
st_dev = np.std(num_data, axis=0)
st_dev

array([2.88675135e+05, 6.89942757e+00, 9.42413867e+00, 1.95641953e+00,
       1.54329611e+01])

Standard Deviation (How far our data lie from our Mean or average)

In [9]:
print("Mean of each column:", st_dev)
print("Standard Deviation of Weekly Self Study Hours: ", st_dev[1].round(2))
print("Standard Deviation of Attendence Percentage: ", st_dev[2].round(2))
print("Standard Deviation of Class Participation: ", st_dev[3].round(2))
print("Standard Deviation of Total Score: ", st_dev[4].round(2))

Mean of each column: [2.88675135e+05 6.89942757e+00 9.42413867e+00 1.95641953e+00
 1.54329611e+01]
Standard Deviation of Weekly Self Study Hours:  6.9
Standard Deviation of Attendence Percentage:  9.42
Standard Deviation of Class Participation:  1.96
Standard Deviation of Total Score:  15.43


The Maximum Weekly Self Study Hours According to the Roll No of the Student

In [10]:
index_of_max_study = np.argmax(num_data[:, 1])

max_total_study = num_data[index_of_max_study, 1]

student_id_with_max_study = num_data[index_of_max_study, 0]

print(f"The maximum total Weekly Study achieved is: {max_total_study}")
print(f"The student ID of the student with this study is: {student_id_with_max_study}")

The maximum total Weekly Study achieved is: 40.0
The student ID of the student with this study is: 210.0


The Minimum Weekly Self Study Hours According to the Roll No of the Student

In [11]:
index_of_min_study = np.argmin(num_data[:, 1])

min_total_study = num_data[index_of_min_study, 1]

student_id_with_min_study = num_data[index_of_min_study, 0]

print(f"The minimum Weekly Study achieved is: {min_total_study}")
print(f"The student ID of the student with this study is: {student_id_with_min_study}")

The minimum Weekly Study achieved is: 0.0
The student ID of the student with this study is: 75.0


The Maximum Attendence Percenatage According to the Roll No of the Student


In [12]:
index_of_max_att = np.argmax(num_data[:, 2])

max_total_att = num_data[index_of_max_att, 2]

student_id_with_max_att = num_data[index_of_max_att, 0]

print(f"The maximum Attendence Percentage achieved is: {max_total_att}")
print(f"The student ID of the student with this percentage is: {student_id_with_max_att}")

The maximum Attendence Percentage achieved is: 100.0
The student ID of the student with this percentage is: 8.0


The Minimum Attendence Percenatage According to the Roll No of the Student


In [13]:
index_of_min_att = np.argmin(num_data[:, 2])

min_total_att = num_data[index_of_min_att, 2]

student_id_with_min_att = num_data[index_of_min_att, 0]

print(f"The minimum Attendence Percentage achieved is: {min_total_att}")
print(f"The student ID of the student with this percentage is: {student_id_with_min_att}")

The minimum Attendence Percentage achieved is: 50.0
The student ID of the student with this percentage is: 991.0


The Maximum Class Participation According to the Roll No of the Student


In [14]:
index_of_max_part = np.argmax(num_data[:, 3])

max_total_part = num_data[index_of_max_part, 3]

student_id_with_max_part = num_data[index_of_max_part, 0]

print(f"The maximum Class Participation achieved is: {max_total_part}")
print(f"The student ID of the student with this participation is: {student_id_with_max_part}")

The maximum Class Participation achieved is: 10.0
The student ID of the student with this participation is: 138.0


The Minimum Class Participation According to the Roll No of the Student


In [15]:
index_of_min_part = np.argmin(num_data[:, 3])

min_total_part = num_data[index_of_min_part, 3]

student_id_with_min_part = num_data[index_of_min_part, 0]

print(f"The minimum Class Participation achieved is: {min_total_part}")
print(f"The student ID of the student with this participation is: {student_id_with_min_part}")

The minimum Class Participation achieved is: 0.0
The student ID of the student with this participation is: 909.0


The Maximum Score According to the Roll No of the Student

In [16]:
index_of_max_score = np.argmax(num_data[:, 4])

max_total_score = num_data[index_of_max_score, 4]

student_id_with_max_score = num_data[index_of_max_score, 0]

print(f"The maximum score achieved is: {max_total_score}")
print(f"The student ID of the student with this score is: {student_id_with_max_score}")

The maximum score achieved is: 100.0
The student ID of the student with this score is: 3.0


The Minimum Score According to the Roll No of the Student

In [17]:
index_of_min_score = np.argmin(num_data[:, 4])

min_total_score = num_data[index_of_min_score, 4]

student_id_with_min_score = num_data[index_of_min_score, 0]

print(f"The minimum score achieved is: {min_total_score}")
print(f"The student ID of the student with this score is: {student_id_with_min_score}")

The minimum score achieved is: 9.4
The student ID of the student with this score is: 114310.0


Now Using all of the Features find the best and the worst student

Best One

In [18]:
index_of_max_score_overall = np.argmax(num_data[:, 4])

max_total_score_overall = num_data[index_of_max_score_overall, 4]

student_id_with_max_score_overall = num_data[index_of_max_score_overall, 0]

best_student_all_features = num_data[index_of_max_score_overall, 1:5]

print(f"The 'best' student (based on highest Total Score) is Student ID: {student_id_with_max_score_overall}")
print(f"Their Total Score is: {max_total_score_overall}")
print(f"Their other performance features (Weekly Self-Study Hours, Attendance Percentage, Class Participation, Total Score) are: {best_student_all_features}")

The 'best' student (based on highest Total Score) is Student ID: 3.0
Their Total Score is: 100.0
Their other performance features (Weekly Self-Study Hours, Attendance Percentage, Class Participation, Total Score) are: [ 19.5  86.3   5.3 100. ]


Worst One

In [19]:
index_of_min_score_overall = np.argmin(num_data[:, 4])

min_total_score_overall = num_data[index_of_min_score_overall, 4]

student_id_with_min_score_overall = num_data[index_of_min_score_overall, 0]

worst_student_all_features = num_data[index_of_min_score_overall, 1:5]

print(f"The 'worst' student (based on lowest Total Score) is Student ID: {student_id_with_min_score_overall}")
print(f"Their Total Score is: {min_total_score_overall}")
print(f"Their other performance features (Weekly Self-Study Hours, Attendance Percentage, Class Participation, Total Score) are: {worst_student_all_features}")

The 'worst' student (based on lowest Total Score) is Student ID: 114310.0
Their Total Score is: 9.4
Their other performance features (Weekly Self-Study Hours, Attendance Percentage, Class Participation, Total Score) are: [ 0.  72.5  3.8  9.4]


Correlation between the Columns

In [24]:
numerical_features = num_data[:, 1:5]
correlation_matrix = np.corrcoef(numerical_features, rowvar=False)

print("Correlation Coefficient Matrix for Numerical Features:")
print(correlation_matrix.round(3))

feature_names = ['Weekly Self-Study Hours', 'Attendance Percentage', 'Class Participation', 'Total Score']
print("\nCorresponding Features:")
for i, name in enumerate(feature_names):
    print(f"Column {i}: {name}")

Correlation Coefficient Matrix for Numerical Features:
[[ 1.    -0.001  0.001  0.812]
 [-0.001  1.    -0.    -0.001]
 [ 0.001 -0.     1.     0.001]
 [ 0.812 -0.001  0.001  1.   ]]

Corresponding Features:
Column 0: Weekly Self-Study Hours
Column 1: Attendance Percentage
Column 2: Class Participation
Column 3: Total Score


This means that:


*   Total Score Increases strongly with the Weekly Self Study Hours and also a bit from the class participation whereas it decreases it a bit from the Attendence Percentage
*   So we can say that the more the weekly self study hours the more score it get

